### ISSUE TITLE
Add ability to wait for pipeline after push

### ISSUE THREAD

**Issue by Ungin** [da-x/glim#1]
Almost always after sending something to gitlab we need the pipeline number (or link)
Do you think it would be possible to implement `--wait-for-pipeline`  option command for `git push` (and similar commands)?
So that it would return pipeline link and pipeline number.
Example:
```
# git push --wait-for-pipeline some/branch
... usual stuff
...
Waiting for gitlab to create pipeline...
Pipeline: 407978
https://git.mynicecompany.com/dev/orion/-/pipelines/407978
```

**Comment by da-x** [comment]
With newest `glim`, you can configure the following alias:

```
[alias]
    wait-for-jobs = !glim from-alias jobs -h `git rev-parse HEAD`
```

And append `; git wait-for-jobs` to the push command.
